# Generated by Django 4.0.5 on 2022-06-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0002_studentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentUser',
        ),
    ]
