# Generated by Django 4.0.5 on 2022-06-21 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App2', '0003_delete_studentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=60, verbose_name='Club')),
                ('field', models.CharField(max_length=100, verbose_name='Field')),
                ('year', models.CharField(max_length=10, verbose_name='Year')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
