# Generated by Django 4.0.5 on 2022-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0004_studentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
