# Generated by Django 4.0.5 on 2022-06-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0005_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
