# Generated by Django 4.0.5 on 2022-07-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0006_delete_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentuser',
        ),
    ]
