# Generated by Django 4.0.5 on 2022-07-03 17:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App2', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event Report')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('body', ckeditor.fields.RichTextField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App2.event')),
                ('report_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
