# Generated by Django 4.0.5 on 2022-07-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0011_alter_student_club_alter_student_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='overseer',
            field=models.CharField(default='NIL', max_length=20, verbose_name='Overseer'),
        ),
    ]
