# Generated by Django 4.0.5 on 2022-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0012_event_overseer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='overseer',
            field=models.CharField(default='', max_length=20, verbose_name='Overseer'),
        ),
    ]
