# Generated by Django 4.0.5 on 2022-07-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0013_alter_event_overseer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_club',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='App2.club'),
        ),
    ]
