# Generated by Django 4.0.5 on 2022-07-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0016_alter_event_attendees_alter_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='overseer',
        ),
    ]
